project:
  type: website

website:
  title: "quarto website example"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - hello.qmd
      - retraction-dates.qmd
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



